[tox]
skipsdist = true
envlist = py{39,310,311,312,313}

[testenv]
commands =
    {envpython} -V
    {envpython} -m compileall speedtest.py
    {envpython} speedtest.py
    {envpython} tests/scripts/source.py

[testenv:flake8]
basepython = python3
deps = flake8
commands =
    flake8 speedtest.py

[testenv:pypy3]
commands =
    pypy3 -V
    pypy3 -m compileall speedtest.py
    pypy3 tests/scripts/source.py
